export const mockProducts = [
  {
    id: 1,
    name: 'Wireless Mouse',
    sku: 'WM-001',
    stock: 45,
    price: 29.99,
    category: 'Electronics',
  },
  {
    id: 2,
    name: 'Mechanical Keyboard',
    sku: 'KB-002',
    stock: 23,
    price: 89.99,
    category: 'Electronics',
  },
  {
    id: 3,
    name: 'USB-C Cable',
    sku: 'CB-003',
    stock: 120,
    price: 12.99,
    category: 'Accessories',
  },
  {
    id: 4,
    name: 'Laptop Stand',
    sku: 'LS-004',
    stock: 8,
    price: 49.99,
    category: 'Accessories',
  },
  {
    id: 5,
    name: 'Monitor 27"',
    sku: 'MN-005',
    stock: 15,
    price: 299.99,
    category: 'Electronics',
  },
  {
    id: 6,
    name: 'Webcam HD',
    sku: 'WC-006',
    stock: 32,
    price: 79.99,
    category: 'Electronics',
  },
  {
    id: 7,
    name: 'Desk Mat',
    sku: 'DM-007',
    stock: 67,
    price: 24.99,
    category: 'Accessories',
  },
  {
    id: 8,
    name: 'Headphones Wireless',
    sku: 'HP-008',
    stock: 19,
    price: 129.99,
    category: 'Electronics',
  },
]
